CPGarageAdmin/Controllers/marketingController.cs
using BAL.Repositories;
using DAL.DBEntities;
using DAL.Models;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.IO;
using System.Linq;
using System.Net.Mail;
using System.Net;
using System.Web;
using System.Web.Mvc;

namespace CPGarageAdmin.Controllers
{
    public class marketingController : Controller
    {
        emailSendRepository emailRepo;
        BaseRepository baserepo;
        public marketingController()
        {
            emailRepo = new emailSendRepository(new Garage_LiveEntities());

            baserepo = new BaseRepository();
        }
        // GET: Marketing
        public ActionResult marketing()
        {
            var AllCustomers = emailRepo.GetUsers();
            ViewBag.AllCustomers = new SelectList(AllCustomers, "UserID", "UserName");

            var Customers = emailRepo.GetCustomerNotification();
            ViewBag.Customers = new SelectList(Customers, "CustomerID", "FullName");

            var CustomerMarketing = emailRepo.GetCustomerMarketing();
            ViewBag.CustomerMarketing = new SelectList(CustomerMarketing, "CustomerID", "FullName");
            return View();
        }
        public ActionResult email()
        {
            var AllCustomers = emailRepo.GetUsers();
            ViewBag.AllCustomers = new SelectList(AllCustomers, "UserID", "UserName");
            return View();
        }
        public ActionResult whatsapp()
        {
            var AllCustomers = emailRepo.GetUsers();
            ViewBag.AllCustomers = new SelectList(AllCustomers, "UserID", "UserName");

            var CustomerMarketing = emailRepo.GetCustomerMarketing();
            ViewBag.CustomerMarketing = new SelectList(CustomerMarketing, "CustomerID", "FullName");

            return View();
        }
        public ActionResult notification()
        {
            var Customers = emailRepo.GetCustomerNotification();
            ViewBag.Customers = new SelectList(Customers, "CustomerID", "FullName");
            return View();
        }
        [HttpPost]
        public ActionResult NotificationSend(EmailSendViewModel model)
        {
            try
            {
                var ds = emailRepo.GetTokens(model.CustomerIDs);
                var lsttoken = JArray.Parse(Newtonsoft.Json.JsonConvert.SerializeObject(ds.Tables[0])).ToObject<List<PushTokenBLL>>();

                foreach (var item in lsttoken)
                {
                    var token = new PushNoticationBLL();
                    token.Title = model.Title2;
                    token.Message = model.PushDescription;
                    token.DeviceID = item.Token;
                    baserepo.PushNotificationAndroid(token);
                    return View();
                }
            }
            catch (Exception ex)
            {
                return View();
            }
            return RedirectToAction("notification");
        }  
            [HttpPost]
        public ActionResult WhatsAppSend(EmailSendViewModel model)
        {
            if (model.WhatsappType == "User")
            {
                var ds = emailRepo.GetUserContactByID(model.Users);
                var lstcustomer = JArray.Parse(Newtonsoft.Json.JsonConvert.SerializeObject(ds.Tables[0])).ToObject<List<User>>();
                foreach (var item in lstcustomer)
                {
                    try
                    {
                        var Contact = item.ContactNo;
                        var Title = model.Title1;
                        var Description = model.WhatsappDescription;

                        string apiUrl = "https://graph.facebook.com/v16.0/104897916024556/messages";
                        string accessToken = "Bearer EAAXW0hLwIIwBOzNXZCdaaeqg7fdsBZB8IWeb7Dl2hh5qWBPvZCxpyC0lbKEJvafy6gKF3dvep9nhzHxukBooe5GZBg6p6BNZB6BAlZBuJK7TMsu4kpMNWQcjhYZBS7DcuANJcZA7F9XiHZAwngMdFWKYSuk8g0BbA7qpgsZAUu9y0Unz2RceZAaUfUmUOJfKFrSpRKAJ9ZCMZASP54AxO7aZAH";

                        string jsonBody = "{" +
                            "\"messaging_product\": \"whatsapp\"," +
                            "\"recipient_type\": \"individual\"," +
                            "\"to\": \"" + Contact + "\"," +
                            "\"type\": \"template\"," +
                            "\"template\": {" +
                            "    \"name\": \"variable_template\"," +
                            "    \"language\": {" +
                            "        \"code\": \"ar\"" +
                            "    }," +
                            "    \"components\": [" +
                            "        {" +
                            "            \"type\": \"header\"," +
                            "            \"parameters\": [" +
                            "                {" +
                            "                    \"type\": \"text\"," +
                            "                    \"text\": \"" + Title + "\"" +
                            "                }" +
                            "            ]" +
                            "        }," +
                            "        {" +
                            "            \"type\": \"body\"," +
                            "            \"parameters\": [" +
                            "                {" +
                            "                    \"type\": \"text\"," +
                            "                    \"text\": \"" + Description + "\"" +
                            "                }" +
                            "            ]" +
                            "        }," +
                            "        {" +
                            "            \"type\": \"button\"," +
                            "            \"sub_type\": \"url\"," +
                            "            \"index\": \"0\"," +
                            "            \"parameters\": [" +
                            "                {" +
                            "                    \"type\": \"text\"," +
                            "                    \"text\": \"home\"" +
                            "                }" +
                            "            ]" +
                            "        }" +
                            "    ]" +
                            "}}";

                        try
                        {
                            HttpWebRequest request = (HttpWebRequest)WebRequest.Create(apiUrl);
                            request.Method = "POST";
                            request.ContentType = "application/json";
                            request.Headers.Add("Authorization", accessToken);

                            using (var streamWriter = new StreamWriter(request.GetRequestStream()))
                            {
                                streamWriter.Write(jsonBody);
                                streamWriter.Flush();
                                streamWriter.Close();
                            }

                            HttpWebResponse response = (HttpWebResponse)request.GetResponse();
                            using (var streamReader = new StreamReader(response.GetResponseStream()))
                            {
                                string responseData = streamReader.ReadToEnd();

                            }
                            return View();
                        }
                        catch (WebException ex)
                        {
                            // Handle any exceptions here
                            Console.WriteLine(ex.Message);
                            return View();
                        }
                    }
                    catch (Exception ex)
                    {

                    }
                }
            }
            else if (model.WhatsappType == "Customer")
            {
                var ds = emailRepo.GetCustomerContactByID(model.Customers);
                var lstcustomer = JArray.Parse(Newtonsoft.Json.JsonConvert.SerializeObject(ds.Tables[0])).ToObject<List<Customer>>();
                foreach (var item in lstcustomer)
                {
                    try
                    {
                        var Contact = item.Mobile;
                        var Title = model.Title1;
                        var Description = model.WhatsappDescription;

                        string apiUrl = "https://graph.facebook.com/v16.0/104897916024556/messages";
                        string accessToken = "Bearer EAAXW0hLwIIwBOzNXZCdaaeqg7fdsBZB8IWeb7Dl2hh5qWBPvZCxpyC0lbKEJvafy6gKF3dvep9nhzHxukBooe5GZBg6p6BNZB6BAlZBuJK7TMsu4kpMNWQcjhYZBS7DcuANJcZA7F9XiHZAwngMdFWKYSuk8g0BbA7qpgsZAUu9y0Unz2RceZAaUfUmUOJfKFrSpRKAJ9ZCMZASP54AxO7aZAH";

                        string jsonBody = "{" +
                            "\"messaging_product\": \"whatsapp\"," +
                            "\"recipient_type\": \"individual\"," +
                            "\"to\": \"" + Contact + "\"," +
                            "\"type\": \"template\"," +
                            "\"template\": {" +
                            "    \"name\": \"variable_template\"," +
                            "    \"language\": {" +
                            "        \"code\": \"ar\"" +
                            "    }," +
                            "    \"components\": [" +
                            "        {" +
                            "            \"type\": \"header\"," +
                            "            \"parameters\": [" +
                            "                {" +
                            "                    \"type\": \"text\"," +
                            "                    \"text\": \"" + Title + "\"" +
                            "                }" +
                            "            ]" +
                            "        }," +
                            "        {" +

CPGarageAdmin/Views/marketing/email.cshtml
@model DAL.Models.EmailSendViewModel
@using System.Web.Configuration;
@{
    ViewBag.Title = "Email Send";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/choices.min.css">
<script src="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/choices.min.js"></script>
<script src="https://cdn.ckeditor.com/4.16.2/standard/ckeditor.js"></script>

<script>
    $(document).ready(function () {
        // Initialize Choices plugin
        var multipleCancelButton = new Choices('#ddlcustomers', {
            removeItemButton: true,
        });

        // Initialize CKEditor
        CKEDITOR.replace('txtdisplayorder');

        // When the form is submitted
        $('#submitButton').on('click', function () {
            // Disable the save button
            $(this).prop('disabled', true);

            // Show loader
            $('#loader').show();

            // Submit the form
            $('#contact-form').submit();
        });
    });
</script>
<style>
    #multipleSelect {
        max-width: 100%;
        width: 100%;
    }

    .choices__list--multiple .choices__item {
        display: inline-block;
        vertical-align: middle;
        border-radius: 20px;
        padding: 4px 10px;
        font-size: 12px;
        font-weight: 500;
        margin-right: 3.75px;
        margin-bottom: 3.75px;
        background-color: #181818;
        border: 1px solid #565656;
        color: #fff;
        word-break: break-all;
    }

    /* Loader styling */
    #loader {
        display: none; /* Hidden by default */
        border: 4px solid #f3f3f3;
        border-radius: 50%;
        border-top: 4px solid #3498db;
        width: 20px;
        height: 20px;
        animation: spin 1s linear infinite;
        margin-left: 10px;
        vertical-align: middle;
    }

    @@keyframes spin {
        0% {
            transform: rotate(0deg);
        }

        100% {
            transform: rotate(360deg);
        }
    }
</style>

@using (Html.BeginForm("EmailSend", "marketing", FormMethod.Post, new { enctype = "multipart/form-data", @id = "contact-form" }))
{
    <div class="controls">
        <div class="row ">
            <div class="col-6 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Email / SMS Marketing</h4>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="exampleInputPassword4">Select Customer</label>
                                    <div class="form-group">
                                        <select id="multipleSelect" multiple name="UserIDs" placeholder="-- Please Select --" data-search="true" data-silent-initial-value-set="true">
                                            @if (ViewBag.AllCustomers != null)
                                            {
                                                foreach (var item in ViewBag.AllCustomers)
                                                {
                                                    <option value="@item.Value">
                                                        @item.Text
                                                    </option>
                                                }
                                            }
                                        </select>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="form_email">Title</label>
                                                @Html.TextBoxFor(model => model.Title, new { @class = "form-control", placeholder = "", @Id = "txtname", name = "Title" })
                                            </div>
                                        </div>
                                        <div class="col-md-12">
                                            <div class="form-group">
                                                <label for="form_need">Subject</label>
                                                @Html.TextBoxFor(model => model.Subject, new { @class = "form-control", placeholder = "", @Id = "txtarname", name = "Subject" })
                                                @Html.ValidationMessageFor(model => model.Subject, "", new { @class = "text-danger" })
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="form_need">Send Type</label>
                                    <br />
                                    <br />
                                    <label>
                                        <a href="~/marketing/email"><input href="~/marketing/email" type="radio" name="Type" value="Email" checked> Email</a>
                                    </label>

                                    <label style=" margin-left: 60px;">
                                        <a href="~/marketing/whatsapp"><input href="~/marketing/whatsapp" type="radio" name="Type" value="WhatsApp"> WhatsApp</a>
                                    </label>

                                    <label style=" margin-left: 60px;">
                                        <a href="~/marketing/notification"><input href="~/marketing/notification" type="radio" name="Type" value="PushNotification">  Push Notification</a>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3" style="padding-top:20px;">
                                <button type="submit" class="btn btn-dark mr-2" id="submitButton">Send Email</button>
                                <div id="loader">
                                    <div class="text-center">
                                        <img src="~/assets/images/loader.gif" width="60px" height="60px" />
                                    </div>
                                </div> <!-- Loader icon -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-6 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="form_email">Description</label>
                                    @Html.TextAreaFor(model => model.Descripiton, new { @class = "form-control", @id = "txtdisplayorder" })
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript" src="~/assets/js/virtual-select.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script type="text/javascript">
    VirtualSelect.init({
        ele: '#multipleSelect'
    });
</script>

CPGarageAdmin/Views/marketing/notification.cshtml
@model DAL.Models.EmailSendViewModel
@using System.Web.Configuration;
@{
    ViewBag.Title = "Notification Send";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<link rel="stylesheet" href="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/choices.min.css">
<script src="https://cdn.jsdelivr.net/gh/bbbootstrap/libraries@main/choices.min.js"></script>

<script>
    $(document).ready(function () {
        // Initialize Choices plugin
        var multipleCancelButton = new Choices('#ddlcustomers', {
            removeItemButton: true,
        });

        // When the form is submitted
        $('#submitButton').on('click', function () {
            // Disable the save button
            $(this).prop('disabled', true);

            // Show loader
            $('#loader').show();

            // Submit the form
            $('#contact-form').submit();
        });
    });
</script>
<style>
    #multipleSelect {
        max-width: 100%;
        width: 100%;
    }

    .choices__list--multiple .choices__item {
        display: inline-block;
        vertical-align: middle;
        border-radius: 20px;
        padding: 4px 10px;
        font-size: 12px;
        font-weight: 500;
        margin-right: 3.75px;
        margin-bottom: 3.75px;
        background-color: #181818;
        border: 1px solid #565656;
        color: #fff;
        word-break: break-all;
    }

    /* Loader styling */
    #loader {
        display: none; /* Hidden by default */
        border: 4px solid #f3f3f3;
        border-radius: 50%;
        border-top: 4px solid #3498db;
        width: 20px;
        height: 20px;
        animation: spin 1s linear infinite;
        margin-left: 10px;
        vertical-align: middle;
    }

    @@keyframes spin {
        0% {
            transform: rotate(0deg);
        }

        100% {
            transform: rotate(360deg);
        }
    }
</style>
@using (Html.BeginForm("NotificationSend", "marketing", FormMethod.Post, new { enctype = "multipart/form-data", @id = "contact-form" }))
{
    <div class="controls">
        <div class="row ">
            <div class="col-6 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Notification Marketing</h4>
                        <label for="exampleInputPassword4">Select Customer</label>
                        <div class="form-group">
                            <select id="multipleSelect" multiple name="CustomerIDs" placeholder="-- Please Select --" data-search="true" data-silent-initial-value-set="true">
                                @if (ViewBag.Customers != null)
                                {
                                    foreach (var item in ViewBag.Customers)
                                    {
                                        <option value="@item.Value">
                                            @item.Text
                                        </option>
                                    }
                                }
                            </select>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="form_email">Title</label>
                                    @Html.TextBoxFor(model => model.Title2, new { @class = "form-control", placeholder = "", @Id = "txtname", name = "Title2" })
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="form_need">Send Type</label>
                                    <br />
                                    <br />
                                    <label>
                                        <a href="~/marketing/email"><input href="~/marketing/email" type="radio" name="Type" value="Email"> Email</a>
                                    </label>

                                    <label style=" margin-left: 60px;">
                                        <a href="~/marketing/whatsapp"><input href="~/marketing/whatsapp" type="radio" name="Type" value="WhatsApp"> WhatsApp</a>
                                    </label>

                                    <label style=" margin-left: 60px;">
                                        <a href="~/marketing/notification"><input href="~/marketing/notification" type="radio" name="Type" value="PushNotification" checked>  Push Notification</a>
                                    </label>
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-md-3" style="padding-top:20px;">
                                <button type="submit" class="btn btn-dark mr-2" id="submitButton">Send Notification</button>
                                <div id="loader">
                                </div> <!-- Loader icon -->
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-6 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group">
                                    <label for="form_email">Notification Message</label>
                                    <textarea class="form-control" name="PushDescription" rows="20"></textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
}

<script type="text/javascript" src="~/assets/js/virtual-select.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>
<script type="text/javascript">
    VirtualSelect.init({
        ele: '#multipleSelect'
    });
</script>